name: 01 - Mi Primer Workflow

# TRIGGER: Cuando se dispara este flujo?
# - Cada vez que se hace push a la rama main
# - Manualmente desde la interfaz de GitHub (workflow_dispatch)
on:
  push:
    branches: [main]
  workflow_dispatch:

# JOBS: Que tareas ejecutamos?
jobs:
  hola-mundo:
    # RUNNER: En que maquina corre? (Ubuntu gratuito de GitHub)
    runs-on: ubuntu-latest

    # STEPS: Pasos secuenciales dentro del job
    steps:
      - name: Saludar desde la nube
        run: echo "Hola Mundo desde GitHub Actions , salududos a mis estudiantres!"

      - name: Mostrar informacion del runner
        run: |
          echo "Sistema operativo: $(uname -s)"
          echo "Fecha y hora UTC: $(date)"
          echo "Usuario: $(whoami)"
          echo "Directorio actual: $(pwd)"
