name: 01 - Flujo Basico (Hola Mundo)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  execute-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sincronizar dependencias
        run: uv sync

      - name: Ejecutar Hola Mundo
        run: uv run python src/hello.py
